### ISSUE TITLE
Don't convert from adventure's `Component` to BungeeCord chat `BaseComponent[]` on Paper

### ISSUE THREAD

**Issue by yusshu** [FixedDev/command-flow#39]
*(commandflow-bukkit)*
Paper supports sending adventure `Component` messages natively.

Maybe add an interface like:
```java
interface ComponentSender {
    void sendMessage(Player player, Component component);
}
```

And create a Paper implementation:
```java
class PaperComponentSender implements ComponentSender {
    @Override
    public void sendMessage(Player player, Component component) {
        player.sendMessage(component); // Paper method 
    }
}
```

And if we are not on Paper, fall back to an implementation that converts components to bungeecord-chat base components.

https://github.com/unnamed/command-flow/blob/master/Bukkit/src/main/java/me/fixeddev/commandflow/bukkit/BukkitCommandWrapper.java#L105

**Comment by yusshu** [comment]
There is a problem, we are on Java 8, Paper is in Java 17. What about...
- Use [adventure-platform-bukkit](https://docs.advntr.dev/platform/bukkit.html)
- Create another Maven module on Java 17 and maybe include it if that's possible?
- Use Gradle! It's possible to just create another sources directory, with a different Java version and dependencies and include its classes in our JAR. [creative-glyphs did that before](https://github.com/unnamed/creative-glyphs/tree/be8f81876001abde3b17ca835d3a464d3e9b5e6c/src), I haven't found a way to do this on Maven.
- Upgrade to Java 17 *(Not really an option, I think many people are still using command-flow on Java 8)*

**Comment by FixedDev** [comment]
Fixed. After this c ommit the message sender was modularized, and one specific for adventure-paper was added.
https://github.com/FixedDev/command-flow/commit/fa993d01b7a1916417bca037435b885b60377acb
